"""user telegram changed2

Revision ID: c68267f4947a
Revises: 87367c8adb05
Create Date: 2024-08-03 11:57:43.058675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68267f4947a'
down_revision = '87367c8adb05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_telegram')
        batch_op.create_index(batch_op.f('ix_user_telegram'), ['telegram'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_telegram'))
        batch_op.create_index('ix_user_telegram', ['telegram'], unique=1)

    # ### end Alembic commands ###
